### ISSUE TITLE
Blank space under "Home"

### ISSUE THREAD

**Issue by LeviSnoot** [jellyfin/JellyfinPlayer#11]
![image](https://user-images.githubusercontent.com/13402525/119531787-90f15580-bd84-11eb-9b27-5c50efa3e000.png)

v1.0.0 (18)
iPhone X

**Comment by acvigue** [comment]
Has the user ever watched any content? This should be fixed in 19
Thanks for reporting!

**Comment by LeviSnoot** [comment]
Yes, at least on other clients. On this client only partway through.

**Comment by acvigue** [comment]
Should be fixed.
